import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import banner_image from "../public/picture/banner.png";
import SearchBox from "../components/SearchBox/SearchBox";
import Layout from "../container/Layout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scorize</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <div className={styles.mainContainer}>
            <div>
              <button className={`text-tertiary-color bg-primary-color rounded p-3 flex mt-32 `}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="white"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="feather feather-send"
                >
                  <line x1="22" y1="2" x2="11" y2="13"></line>
                  <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
                </svg>
                مهاجرت تضمینی
              </button>
              <h1 className={styles.h1}>
                مهاجرت تضمینی به خارج از کشور با{" "}
                <button className=" text-primary-color border border-primary-color rounded-2xl pl-2 pr-2 ">اسکورایز</button>
              </h1>
              <SearchBox />
            </div>
            <div className="banner">
              <Image src={banner_image} className={styles.bannerImage}></Image>
            </div>
          </div>
        </main>
      </Layout>
    </div>
  );
}
